# Generated by Django 5.0 on 2025-04-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0116_flymasterdata_alter_contestant_air_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='prohibited_zone_maximum',
            field=models.FloatField(default=3, help_text='The maximum score that can be given for entering prohibited zones. Negative numbers means the maximum is ignored'),
        ),
    ]
