# Generated by Django 5.0 on 2025-04-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0117_scorecard_prohibited_zone_maximum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='prohibited_zone_maximum',
            field=models.FloatField(default=-1, help_text='The maximum score that can be given for entering prohibited zones. Negative numbers means the maximum is ignored'),
        ),
    ]
